name: clang-format-lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  formatting-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: '.'
        extensions: 'h,cpp'
        clangFormatVersion: 9
